spring:
  data:
    mongodb:
#      uri: mongodb+srv://ashitosh:ashitosh@cluster0.bdfu8ip.mongodb.net/?appName=Cluster0
      uri: mongodb://localhost:27017/
      database: journaldb
      auto-index-creation: true

server:
  port: 8080